package com.atguigu.mybatis.bean;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.id
     *
     * @mbg.generated Mon Jun 03 04:21:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dept.department
     *
     * @mbg.generated Mon Jun 03 04:21:48 CST 2019
     */
    private String department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.id
     *
     * @return the value of tbl_dept.id
     *
     * @mbg.generated Mon Jun 03 04:21:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.id
     *
     * @param id the value for tbl_dept.id
     *
     * @mbg.generated Mon Jun 03 04:21:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dept.department
     *
     * @return the value of tbl_dept.department
     *
     * @mbg.generated Mon Jun 03 04:21:48 CST 2019
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dept.department
     *
     * @param department the value for tbl_dept.department
     *
     * @mbg.generated Mon Jun 03 04:21:48 CST 2019
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }
}